### ISSUE TITLE
Help with API

### ISSUE THREAD

**Issue by LarryBattle** [IainNZ/SimplexJS#1]
Cool project but how would I use it to solve this problem?

Maximize, z = x1 + 2x2 - x3

Constraints:
2x1 + 2x2 + x3 <= 14
4x1 + 2x2 + 3x3 <= 28
2x1 + 5x2 + 5x3 <= 30

0 <= x1, 0 <= x2, 0 <= x3

**Comment by IainNZ** [comment]
Currently you'd need to reformulate to standard computational form yourself. 
I hope to add a basiic modelling language, and make the algorithm competitive, one day.

**Comment by LarryBattle** [comment]
So what do I do next after converting to standard computational form?

maximize z = x1 + 2x2 - x3
where 
slack1 + 2x1 + 2x2 + x3 = 14
slack2 + 4x1 + 2x2 + 3x3 = 28
slack3 + 2x1 + 5x2 + 5x3 = 30

Side note: 
You might be able to use my library. But it's still in beta and rather heavy. 
https://github.com/LarryBattle/YASMIJ.js

Example: 

```
// Input

var type = "maximize",
 z = "x1 + 2x2 - x3",
 constraints = [ 
    "2x1 + 2x2 + x3 <= 14", 
    "4x1 + 2x2 + 3x3 <= 28", 
    "2x1 + 5x2 + 5x3 <= 30" 
]
Input.parse( type, z, constraints).convertToStandardForm().toString();

// outputs
"maximize z = x1 + 2x2 - x3, where slack1 + 2x1 + 2x2 + x3 = 14, slack2 + 4x1 + 2x2 + 3x3 = 28, slack3 + 2x1 + 5x2 + 5x3 = 30"
```

**Comment by IainNZ** [comment]
You build an object, and set number of variables, number of constraints, the dense A matrix, b vector, c vector, and x lower and upper bounds. Check out the TSP example.

**Comment by IainNZ** [comment]
Your code looks like it could be configured to work with it. It seems you are using the full simplex method with rational numbers, judging by the output?
